config/routes.rb
Rails.application.routes.draw do
  # resources :users, only: [:new, :create]
  root 'sessions#welcome'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  get 'authorized', to: 'sessions#page_requires_login'

  # resources :likes
  resources :movies
  get 'search', to: 'movies#search'
  resources :reviews
  # resources :users
  get "/users", to: 'users#index', as: "users" # index
  get '/users/new', to: 'users#new', as: 'new_user' #new
  post '/users', to: 'users#create' #create
  get "/users/:id", to: "users#show", as: "user" #show
  get "/users/:id/edit", to: 'users#edit', as: "edit_user" #edit
  patch "/users/:id", to: 'users#update' #update
  delete "/users/:id", to: 'users#destroy' #destroy
  post '/logout', to: 'users#logout'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord

end

app/models/movie.rb
class Movie < ApplicationRecord
    has_many :reviews, dependent: :destroy
    has_many :users, through: :reviews 
    has_one_attached :image, :dependent => :destroy

    # title must not be nil
    validates :title, presence: true

    # description must not be nil
    validates :description, presence: true

    end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :movie

  # description must not be nil
  # validates :description, presence: true

end

app/models/user.rb
class User < ApplicationRecord
    has_many :reviews, dependent: :destroy
    has_many :movies, through: :reviews
    
    has_secure_password

    # username must not be nil
    validates :username, presence: true

    # username cannot already exist
    validates :username, uniqueness: { case_sensitive: false } 
    
    #first_name must not be nil
    validates :first_name, presence: true
    
    #last_name must not be nil
    validates :last_name, presence: true
    
    # email must not be nil
    validates :email, presence: true
    
    # email must be in an email format
    validates_format_of :email, :with => /\A[^@,\s]+@[^@,\s]+\.[^@,\s]+\z/
    
    # email must be unique
    validates :email, uniqueness: { case_sensitive: false }
    
    # password must not be nil
    validates :password_digest, presence: true


    def full_name
        self.first_name + " " + self.last_name
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authorized
    helper_method :current_user
    helper_method :logged_in?

    def current_user    
        User.find_by(id: session[:user_id])  
    end

    def logged_in?
       
        !!current_user
    end

    def authorized
        redirect_to '/welcome' unless logged_in?
     end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
    skip_before_action :authorized, only: [:new, :create]
    
    def index
        @movies = Movie.all
    end

    def search
        @movies = Movie.where("title LIKE ?", "%" + params[:q] + "%")
    end

    def show
        @movie = Movie.find(params[:id])
    end

    def new
        @errors = flash[:errors]
        @movie = Movie.new
        render :new
    end

    def create
        movie_params = params.require(:movie).permit(:title, :genre, :description, :rating, :image)
        @movie = Movie.create(movie_params)
        if @movie.valid?
            redirect_to movie_path(@movie)
        else
            flash[:errors] = @movie.errors.full_messages
            redirect_to new_movie_path(@movie)
        end
    end

    def edit
        @errors = flash[:errors]
        @movie = Movie.find(params[:id])
        render :edit
    end

    def update
        movie = Movie.find(params[:id])
        movie_params = params.require(:movie).permit(:title, :genre, :description, :rating, :image)
        if movie.valid?
            movie.update(movie_params)
            redirect_to movie_path(movie)
        else
            flash[:errors] = movie.errors.full_messages
            redirect_to edit_movie_path(movie)
        end
    end

    def destroy
        movie = Movie.find(params[:id])
        # movie.rooms.destroy_all
        movie.destroy

        redirect_to movies_path
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]
  def index
    @reviews = Review.all
  end

  def show
    @review = Review.find(params[:id])
  end

  def new
    @errors = flash[:errors]
    @review = Review.new
    @review.user_id = current_user.id
    render :new
  end

  def create
    review = Review.create(review_params)
    review.user_id = current_user.id
    if review.valid?
      review.time_posted = Time.now

      redirect_to reviews_path
    else
      flash[:errors] = review.errors.full_messages
      redirect_to new_review_path(review)
    end

  end

  def edit
    @errors = flash[:errors]
    @review = Review.find(params[:id])
    render :edit
  end

  def update
    review = Review.find(params[:id])
    if review.valid?
      review.update(review_params)

      redirect_to review_path(review)
    else
      flash[:errors] = review.errors.full_messages
      redirect_to edit_review_path(review)
    end
  end

  def destroy
    review = Review.find(params[:id])
    review.destroy

    redirect_to reviews_path
  end

  private

  def review_params
    params.require(:review).permit(:description, :user_id, :movie_id, :date_posted, :movie_rating)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized, only: [:new, :create, :welcome]

  def new
  end

  def create
    @user = User.find_by(username: params[:username])
   if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to '/welcome'
   else
      
      redirect_to '/login'
   end

  end

  def welcome
  end

  def page_requires_login
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]

  def index
    @users = User.all
  end

  def show
    # @user = User.find(params[:id])
    @user = User.find_by(id: session[:user_id]) 
  end

  def new
    @errors = flash[:errors]
    @user = User.new
    render :new
  end

  def create
    @user = User.create(user_params)
    if @user.valid?
      session[:user_id] = @user.id
      redirect_to '/welcome'

      # redirect_to user_path(user)
    else
      flash[:errors] = user.errors.full_messages
      redirect_to new_user_path(user)
    end
  end

  def edit
    @errors = flash[:errors]
    @user = User.find_by(id: session[:user_id])
    render :edit
  end

  def update
    user = User.find_by(id: session[:user_id])

    if user.valid?
      user.update(user_params)
      redirect_to user_path(user)
    else
      flash[:errors] = user.errors.full_messages
      redirect_to edit_user_path(user)
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to welcome_path
  end

  def destroy
    user = User.find_by(id: session[:user_id])
    user.destroy

    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :first_name, :last_name, :password, :email)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<!-- Grey with black text -->

<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <ul class="navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href=<%=root_path%>>CINEMADDICT</a>
    </li>
    <li class="nav-item">
      <% if logged_in? %>
      <a class="nav-link" href=<%=user_path(session[:user_id])%>>Profile</a>
      <% else %>
      <a class="nav-link" href=<%=login_path%>>Profile</a>
      <% end %>
    </li>
    <li class="nav-item">
      <a class="nav-link" href= <%=movies_path%> >Movies</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href=<%=new_movie_path%>>Add Movie</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href=<%=reviews_path%>>Reviews</a>
    </li>
    
  </ul>
    <form class="form-inline" action="/search">
    <input class="form-control mr-sm-2" name="q" type="text" placeholder="Search">
    <button class="btn btn-outline-success" type="submit">Search</button>
  </form>
</nav>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if logged_in? %>
          <li><%= link_to "New Movie", new_movie_path, class: "active" %></li>
          <li><%= link_to "Account", user_path(session[:user_id]) %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_path, class: "active" %></li>
          <li><%= link_to "Sign In", login_path, class: "active" %></li>
        <% end %>
      </ul>
      <%= form_tag search_path, method: :get, class: "navbar-form navbar-right", role: "search" do %>
        <p>
          <%= text_field_tag :search, params[:search], class: "form-control" %>
          <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
        </p>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CinemaddictApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>
    <%= render 'layouts/header' %>
    <div class="container">
   <%= yield %>
   </div>
    </body>
</html>

app/views/movies/edit.html.erb
<h1>Edit Form For <%= @movie.title %></h1>
<hr>
<% if @errors %>
    <% @errors.each do |error| %>
      <p style="color:red"><%= error %></p>
    <% end %>
  <% end %>
<%= form_for @movie do |f| %>
    <%= f.label :title %>
        <%= f.text_field :title %>
        <br>
        <br>
        <%= f.label :description %>
        <%= f.text_field :description %>
        <br>
        <br>
        <%= f.label :genre %>
        <%= f.select :genre, ['Action', 'Adventure', 'Animation / Anime', 'Biopic', 'Childrens', 'Comedy', 'Crime', 'Detective/Spy', 'Documentary', 'Drama', 'Horror', 'Family', 'Fantasy', 'Historical', 'Musical', 'Romance', 'Sport', 'Sci-Fi', 'Thriller / Suspense','War', 'Western'] %>
        <br>
        <br>
        <%= f.label :rating %>
        <%= f.select :rating, ['G', 'PG', 'PG-13', 'R', 'NC-17']%>
        <br>
        <br>
        <div class="form-group">
          <% if @movie.image.attached? %>
            <%= image_tag @movie.image, style: "width: 200px; display: block" %>
          <% end %>

          <%= f.label :image %>
          <%= f.file_field :image, class: "form-control" %>
        </div>
    <%= f.submit "Edit" %>
<% end %>

app/views/movies/index.html.erb
  <h1>Move List</h1>
  <% @movies.each do |movie| %>
    <ul>
        <%= image_tag movie.image, style: "width: 250px; display: block" %>
        <h5><%= link_to "#{movie.title}", movie_path(movie) %></h5>
        <li><%= "Genre: #{movie.genre}" %></li>
        <li><%= "Description: #{movie.description}" %></li>
        <li><%= "Rating: #{movie.rating}" %></li>
    </ul>
  <% end %>
  

app/views/movies/new.html.erb
<h1>Add New Movie</h1>
<br>
<% if @errors %>
    <% @errors.each do |error| %>
      <p style="color:red"><%= error %></p>
    <% end %>
  <% end %>
<%= form_for @movie do |f| %>
    <%= f.label :title %><br>
        <%= f.text_field :title %>
        <br>
        <br>
        <%= f.label :description %><br>
        <%= f.text_area :description %>
        <br>
        <br>
        <%= f.label :genre %><br>
        <%= f.select :genre, ['Action', 'Adventure', 'Animation / Anime', 'Biopic', 'Childrens', 'Comedy', 'Crime', 'Detective/Spy', 'Documentary', 'Drama', 'Horror', 'Family', 'Fantasy', 'Historical', 'Musical', 'Romance', 'Sport', 'Sci-Fi', 'Thriller / Suspense','War', 'Western'] %>
        <br>
        <br>
        <%= f.label :rating %><br>
        <%= f.select :rating, ['G', 'PG', 'PG-13', 'R', 'NC-17']%>
        <br>
        <br>
        <div class="form-group">
          <% if @movie.image.attached? %>
            <%= image_tag @movie.image, style: "width: 200px; display: block" %>
          <% end %>

          <%= f.label :image %>
          <%= f.file_field :image, class: "form-control" %>
        </div>

    <input type="submit" class="btn btn-info" value="Submit">
<% end %>

app/views/movies/search.html.erb
<h1>Search Results</h1>
<% if @movies.empty?  %>

<h1>Sorry We Couldn't Find That Movie</h1>
<% else %>
<% @movies.each do |movie| %>
    <ul>
        <%= image_tag movie.image, style: "width: 200px; display: block" %>
        <h5><%= link_to "#{movie.title}", movie_path(movie) %></h5>
        <li><%= "Genre: #{movie.genre}" %></li>
        <li><%= "Description: #{movie.description}" %></li>
        <li><%= "Rating: #{movie.rating}" %></li>
    </ul>
  <% end %>

  <% end %>

app/views/movies/show.html.erb
<div class="container" style="margin-top:30px">
  <div class="row">
    <div class="col-sm-4">
      <h2><%= @movie.title %></h2>
      <% if @movie.image.attached? %>
        <!-- @movie.image.present? will always return true, use attached? to check presence -->
        <p>
            <%= image_tag @movie.image.variant(resize: "500x500") %>
        </p>
        <% end %>
      <p>Genre: <%= @movie.genre %></p>
      <p>Description: <%= @movie.description %></p>
      <p>Rating: <%= @movie.rating %></p>
      <h3>User Options</h3>
      <p>What would you like to do next?</p>
      <ul class="nav nav-pills flex-column">
        <li class="nav-item">
          <a class="nav-link active" href=<%=new_review_path%>>Write A Review</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href=<%=edit_movie_path(@movie)%>>Update Movie Info</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#"></a>
        </li>
      </ul>
      <hr class="d-sm-none">
    </div>
    <div class="col-sm-8">
        <% if !@movie.reviews.empty? %>
            <% Review.all.each do |review| %>
                <% if review.movie_id == @movie.id  %>
                <h2><%= review.description.slice(0..20) %>...</h2>
                <h5>Cinemaddict Rating:</h5>
                    <% times = review.movie_rating %>
                    <% while times > 0 do %>
                    <span class="fa fa-star checked"></span>
                    <% times-=1 %>
                    <% end %>
                <br>
                <h5>reviewed by: <%= review.user.username %></h5>
                <br>
                <p><%= review.description %></p>
                <br>
                <p><%= "Posted: #{review.created_at.strftime("%a %b %e %T %Y")}" %></p>
                <% end %>
            <% end %>
        
        <% else %>
            
            <br>
            <br>
            <h2>Be the first to review this movie!</h2>
        <% end %>
    </div>
  </div>
</div>

app/views/reviews/_form.html.erb
<%= form_for @review do |f| %>
  <%= f.label :user_id %>
  <%= f.select :user_id, [[current_user.first_name, current_user.id]] %>
  <br>
  <br>
  <%= f.label :movie_rating %>
  <%= f.select :movie_rating, [1,2,3,4,5] %>
  <br>
  <br>
  <%= f.label :movie_id %>
  <%= f.collection_select(:movie_id, Movie.all, :id, :title) %>
  <br>
  <br>
  <%= f.label :description %><br>
  <%= f.text_area :description, placeholder: "Write review here..." %>
  <br>
  <br>
  <input type="submit" class="btn btn-info" value="Create Review">
<% end %>

app/views/reviews/edit.html.erb
<% if current_user.id == @review.user.username %>
 <%= render 'form' %>
<% else %>
<h1>You cannot edit another person's review</h1>
<p><%=link_to 'Write your own review here', new_review_path %></p>
<% end %>

app/views/reviews/index.html.erb
<h1>Movie Reviews</h1>

<br>
<% @reviews.each do |review| %>
    <h4><%= link_to "#{review.description.slice(0..29)}...", review_path(review)%></h4>
    <ul>
        <li>Movie: <%= link_to Movie.find(review.movie_id).title, movie_path(review.movie_id) %></li>
        <li>Reviewed by: <%= User.find(review.user_id).username%></li>
        <li><%= "Description: #{review.description}" %></li>
    </ul>
<% end %>

<%= link_to "Write A Review", new_review_path %>

app/views/reviews/new.html.erb
<h1>New review</h1>

<% if @errors %>
    <% @errors.each do |error| %>
      <p style="color:red"><%= error %></p>
    <% end %>
  <% end %>
  <% if logged_in? %>
    <%= render 'form' %>
  <% else %>
  <div class="alert alert-danger">
    <strong>Sorry!</strong> You must be <a href="welcome_path" class="alert-link">logged in to write a review.</a>.
  </div>
  <% end %>

app/views/reviews/show.html.erb
<h1>Review for <%= Movie.find(@review.movie_id).title %></h1>
    <ul>
        <li>Movie: <%= link_to Movie.find(@review.movie_id).title, movie_path(@review.movie_id) %></li>
        <li>User: <%= link_to User.find(@review.user_id).username, user_path(@review.user_id) %></li>
        <li><%= "Description: #{@review.description}" %></li>
        <%# <%byebug%>
        <li><%= "Time Posted: #{@review.created_at.strftime("%a %b %e %T %Y")}" %></li>
    </ul>

<%= link_to "Main Menu", '/welcome' %> | <%= link_to "Edit Review", edit_review_path(@review) %> | <%= link_to "All reviews", reviews_path %>
<br>
<br>
<%= button_to "Remove Review", review_path(@review), :method => :delete %>

app/views/users/edit.html.erb
<h1>Edit <%= @user.username %></h1>

<% if @errors %>
    <% @errors.each do |error| %>
      <p style="color:red"><%= error %></p>
    <% end %>
  <% end %>
<%= form_for @user do |f| %>
  <%= f.label :username %>:
  <%= f.text_field :username %>
  <br>
  <br>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  <br>
  <br>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  <br>
  <br>
  <%= f.label :password %>
  <%= f.text_field :password %>
  <br>
  <br>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <br>
  <br>
  <%= f.submit :update %>
<% end %>
<br>
<%= link_to "Go back", user_path(@user) %>

app/views/users/index.html.erb
  <h1>All users</h1>
  <%= link_to "Create User", new_user_path %>
  <ol>
  <% @users.each do |user| %>
    <li>Name: <%= link_to user.full_name, user %></li>
  <% end %>
  </ol>

app/views/users/new.html.erb
<h1>Create new User</h1>

<% if @errors %>
    <% @errors.each do |error| %>
      <p style="color:red"><%= error %></p>
    <% end %>
  <% end %>
<%= form_for @user do |f| %>
  <%= f.label :username %>:
  <%= f.text_field :username %>
  <br>
  <br>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  <br>
  <br>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  <br>
  <br>
  <%= f.label :password %>
  <%= f.text_field :password %>
  <br>
  <br>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <br>
  <br>
  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<div class="jumbotron text-center" style="margin-bottom:0">
  <h1><%= "Welcome Back #{@user.first_name}" %></h1>
  <p>Great to see you again!</p> 
</div>

<div class="container" style="margin-top:30px">
  <div class="row">
    <div class="col-sm-4">
      <h2><%= @user.username %></h2>

      <p>Total reviews written: <%= @user.reviews.length %></p>
      <h3>User Options</h3>
      <p>What would you like to do next?</p>
      <ul class="nav nav-pills flex-column">
        <li class="nav-item">
          <a class="nav-link active" href=<%=new_review_path%>>Write A Review</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href=<%=edit_user_path%>>Edit Your Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#"></a>
        </li>
      </ul>
      <hr class="d-sm-none">
    </div>
    <div class="col-sm-8">
      <% Review.all.each do |review| %>
          <% if review.user_id == session[:user_id]  %>
          <h2><%= review.description.slice(0..20) %></h2>
          <h4><%= review.movie.title %></h4>
          <h5>Cinemaddict Rating:</h5>
            <% times = review.movie_rating %>
            <% while times > 0 do %>
              <span class="fa fa-star checked"></span>
              <% times-=1 %>
            <% end %>
          <br>
          <br>
          <p><%= review.description.slice(0..100) %></p>
          <br>
          <p><%= "Posted: #{review.created_at.strftime("%a %b %e %T %Y")}" %></p>
          <% end %>
      <% end %>
    </div>
  </div>
</div>